name:                sql-friendo
version:             0.1.0.0
github:              "danilobiella/sql-friendo"
license:             BSD3
author:              "Danilo Biella"
maintainer:          "d.biella@gmail.com"
copyright:           "2024 Danilo Biella"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- megaparsec
- pretty-show
- semigroupoids
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  sql-friendo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql-friendo

tests:
  sql-friendo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sql-friendo
    - QuickCheck
    - HUnit
